// This is an autogenerated file from Firebase Studio.
import { notFound } from 'next/navigation';
import { forumPosts } from '@/lib/mock-data';
import type { ForumPost } from '@/lib/types';
import { ForumPostClient } from '@/components/community/ForumPostClient';
import { getPostWithLocalStorage } from '@/lib/data-helpers';

export default async function ForumPostPage({ params }: { params: { id: string } }) {
  // This page is a server component, so we can't use hooks.
  // We can only pass the initial data to the client component.
  // The client component will then be responsible for checking localStorage.
  const post: ForumPost | undefined = forumPosts.find(p => p.id === params.id);

  if (!post) {
    // In a real app with a DB, we would also check our localStorage mock here
    // But for now, if it's not in the initial data, we'll consider it not found on the server.
    notFound();
  }

  return <ForumPostClient post={post} />;
}
