// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that generates a blog post on a given topic.
 *
 * - generateBlogPost - A function that handles the blog post generation process.
 * - GenerateBlogPostInput - The input type for the generateBlogPost function.
 * - GenerateBlogPostOutput - The return type for the generateBlogPost function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateBlogPostInputSchema = z.object({
  topic: z.string().describe('The topic for the blog post.'),
});
export type GenerateBlogPostInput = z.infer<typeof GenerateBlogPostInputSchema>;

const GenerateBlogPostOutputSchema = z.object({
  title: z.string().describe('The catchy title of the blog post.'),
  content: z.string().describe('The full content of the blog post in Markdown format. It should be comprehensive, engaging, and well-structured with headings and paragraphs.'),
  category: z.string().describe('A relevant category for the blog post (e.g., "Tips & Tricks", "Ethical Fashion", "Brand Spotlight").'),
});
export type GenerateBlogPostOutput = z.infer<typeof GenerateBlogPostOutputSchema>;

export async function generateBlogPost(input: GenerateBlogPostInput): Promise<GenerateBlogPostOutput> {
  return generateBlogPostFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateBlogPostPrompt',
  input: {schema: GenerateBlogPostInputSchema},
  output: {schema: GenerateBlogPostOutputSchema},
  prompt: `You are an expert content writer for EcoChic, a brand focused on sustainable and ethical e-commerce.

  Your task is to write an engaging and informative blog post about the following topic: {{{topic}}}.

  The blog post should be well-structured, easy to read, and provide valuable insights to the reader.
  Use Markdown for formatting, including headings (#, ##), bold text, and lists where appropriate.
  The tone should be optimistic, inspiring, and aligned with the EcoChic brand.
  
  Please generate a complete blog post with a title and a relevant category.`,
});


const generateBlogPostFlow = ai.defineFlow(
  {
    name: 'generateBlogPostFlow',
    inputSchema: GenerateBlogPostInputSchema,
    outputSchema: GenerateBlogPostOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
