import type { Product, BlogPost, ForumPost } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Cotton T-Shirt',
    description: 'A soft, comfortable t-shirt made from 100% organic cotton, grown without harmful pesticides.',
    category: 'Apparel',
    price: 1999,
    images: ['/cotton-eco-threads1.png', '/cotton-eco-threads2.png', '/cotton-eco-threads3.png'],
    greenScore: 9,
    carbonFootprint: '2.1 kg CO₂e',
    certifications: ['GOTS', 'Fair Trade'],
    brand: 'EcoThreads',
    reviews: {
      rating: 4.8,
      count: 120,
      items: [
        { id: 'r1', author: 'Jane D.', rating: 5, date: '2024-05-10', comment: 'Incredibly soft and fits perfectly. You can feel the quality. Worth every penny!' },
        { id: 'r2', author: 'Mike P.', rating: 4, date: '2024-05-12', comment: 'Great t-shirt, very comfortable. I wish it came in more colors though.' },
        { id: 'r3', author: 'Sarah K.', rating: 5, date: '2024-05-15', comment: 'My new favorite shirt. I love that it\'s ethically made.' },
      ],
    },
  },
  {
    id: '2',
    name: 'Recycled Glass Tumblers',
    description: 'Set of four drinking glasses made from 100% recycled glass, perfect for any beverage.',
    category: 'Home Goods',
    price: 299,
    images: ['/recycled-glass-tumblers1.png', '/recycled-glass-tumblers2.png'],
    greenScore: 8,
    carbonFootprint: '1.5 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'GreenGlass',
    reviews: {
      rating: 4.9,
      count: 85,
      items: [
        { id: 'r4', author: 'Tom W.', rating: 5, date: '2024-04-20', comment: 'These glasses are beautiful and have a nice weight to them. Very high quality.' },
        { id: 'r5', author: 'Emily R.', rating: 5, date: '2024-04-25', comment: 'I love the subtle green tint. They look great in my kitchen.' },
      ],
    },
  },
  {
    id: '3',
    name: 'Bamboo Toothbrush Set',
    description: 'A pack of four biodegradable toothbrushes with handles made from sustainably sourced bamboo.',
    category: 'Personal Care',
    price: 999,
    images: ['/bamboo-toothbrush-set.png'],
    greenScore: 10,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'NatureBrush',
    reviews: {
      rating: 4.7,
      count: 213,
      items: [
        { id: 'r6', author: 'David L.', rating: 5, date: '2024-05-01', comment: 'Good for my teeth and good for the planet. Makes me happy.' },
        { id: 'r7', author: 'Jessica M.', rating: 4, date: '2024-05-05', comment: 'The bristles are a bit softer than I expected, but it cleans well.' },
      ],
    },
  },
  {
    id: '4',
    name: 'All-Natural Soy Candle',
    description: 'A hand-poured candle made with natural soy wax and essential oils, in a reusable jar.',
    category: 'Home Goods',
    price: 1499,
    images: ['/all-natural-soy-candle.png'],
    greenScore: 7,
    carbonFootprint: '0.8 kg CO₂e',
    certifications: ['Vegan'],
    brand: 'AuraScents',
    reviews: {
      rating: 4.6,
      count: 98,
      items: [],
    },
  },
  {
    id: '5',
    name: 'Reusable Shopping Bag',
    description: 'Durable and foldable shopping bag made from recycled plastic bottles. Say no to single-use plastic.',
    category: 'Accessories',
    price: 799,
    images: ['/reusable-shopping-bag.png'],
    greenScore: 10,
    carbonFootprint: '0.5 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'CarryGreen',
    reviews: {
      rating: 5.0,
      count: 301,
      items: [],
    },
  },
  {
    id: '6',
    name: 'Hemp Backpack',
    description: 'A stylish and durable backpack made from natural hemp fiber, a highly sustainable crop.',
    category: 'Accessories',
    price: 5999,
    images: ['/hemp-backpack.png'],
    greenScore: 9,
    carbonFootprint: '4.5 kg CO₂e',
    certifications: ['Organic'],
    brand: 'HempWorks',
    reviews: {
      rating: 4.8,
      count: 55,
      items: [],
    },
  },
   {
    id: '7',
    name: 'Upcycled Denim Jacket',
    description: 'A classic denim jacket given a new life through creative upcycling. Each piece is unique.',
    category: 'Apparel',
    price: 7499,
    images: ['/upcycled-denim-jacket.png'],
    greenScore: 8,
    carbonFootprint: '3.2 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'ReJean',
    reviews: {
      rating: 4.9,
      count: 42,
      items: [],
    },
  },
  {
    id: '8',
    name: 'Cork Yoga Mat',
    description: 'An antimicrobial and non-slip yoga mat made from sustainable cork and natural rubber.',
    category: 'Fitness',
    price: 4999,
    images: ['/cork-yoga-mat.png'],
    greenScore: 9,
    carbonFootprint: '2.8 kg CO₂e',
    certifications: ['FSC Certified Cork'],
    brand: 'ZenCork',
    reviews: {
      rating: 4.7,
      count: 76,
      items: [],
    },
  },
  {
    id: '9',
    name: 'Compostable Phone Case',
    description: 'A durable and stylish phone case that fully breaks down in a compost environment at its end-of-life.',
    category: 'Electronics Accessories',
    price: 2499,
    images: ['/compostable-phone-case1.png'],
    greenScore: 9,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['Biodegradable'],
    brand: 'EcoGuard',
    reviews: {
      rating: 4.5,
      count: 110,
      items: [
        {
          id: 'r8',
          author: 'Alex B.',
          rating: 4,
          date: '2024-06-01',
          comment: 'Fits well and I love knowing it\'s good for the planet. Feels a bit different than plastic, but in a good way.',
        },
        {
          id: 'r9',
          author: 'Chloe L.',
          rating: 5,
          date: '2024-06-05',
          comment: 'Sleek design and eco-friendly. What more could you ask for?',
        },
      ],
    },
  },
  {
    id: '10',
    name: 'Solar-Powered Garden Lights (Set of 4)',
    description: 'Bright and energy-efficient garden lights powered entirely by solar energy, reducing your electricity bill.',
    category: 'Outdoor & Garden',
    price: 3999,
    images: ['/solar-garden-lights1.png',],
    greenScore: 10,
    carbonFootprint: '0.0 kg CO₂e (operational)',
    certifications: ['Energy Star'],
    brand: 'SunBeam',
    reviews: {
      rating: 4.6,
      count: 150,
      items: [
        {
          id: 'r10',
          author: 'Mark J.',
          rating: 5,
          date: '2024-05-20',
          comment: 'Easy to install and provide great illumination. Perfect for my walkway.',
        },
        {
          id: 'r11',
          author: 'Sophia H.',
          rating: 4,
          date: '2024-05-22',
          comment: 'They look nice and work reliably. One light occasionally seems a bit dimmer than the others.',
        },
      ],
    },
  },
  {
    id: '11',
    name: 'Stainless Steel Reusable Water Bottle',
    description: 'A durable, insulated water bottle made from high-quality food-grade stainless steel, keeps drinks cold for hours.',
    category: 'Kitchen & Dining',
    price: 1899,
    images: ['/stainless-steel-water-bottle1.png',],
    greenScore: 8,
    carbonFootprint: '0.7 kg CO₂e',
    certifications: ['BPA Free'],
    brand: 'AquaSustain',
    reviews: {
      rating: 4.9,
      count: 280,
      items: [
        {
          id: 'r12',
          author: 'Olivia M.',
          rating: 5,
          date: '2024-06-10',
          comment: 'My favorite water bottle! No more plastic. Keeps my water ice cold all day.',
        },
        {
          id: 'r13',
          author: 'Ethan K.',
          rating: 5,
          date: '2024-06-12',
          comment: 'Solid build, easy to clean. Highly recommend.',
        },
      ],
    },
  },
  {
    id: '12',
    name: 'Biodegradable Kitchen Sponges (Pack of 3)',
    description: 'Eco-friendly kitchen sponges made from plant-based materials, fully compostable after use.',
    category: 'Home Goods',
    price: 899,
    images: ['/biodegradable-sponges.png'],
    greenScore: 9,
    carbonFootprint: '0.2 kg CO₂e',
    certifications: ['Plant-Based'],
    brand: 'CleanEarth',
    reviews: {
      rating: 4.4,
      count: 90,
      items: [],
    },
  },
  {
    id: '13',
    name: 'Wool Dryer Balls (Set of 6)',
    description: 'Natural alternative to dryer sheets, reduces drying time and static cling, made from 100% New Zealand wool.',
    category: 'Laundry',
    price: 1599,
    images: ['/wool-dryer-balls.png'],
    greenScore: 9,
    carbonFootprint: '0.4 kg CO₂e',
    certifications: ['Cruelty-Free'],
    brand: 'FluffyEco',
    reviews: {
      rating: 4.7,
      count: 180,
      items: [],
    },
  },
  {
    id: '14',
    name: 'Eco-Friendly Laundry Detergent Pods (60 count)',
    description: 'Highly concentrated laundry detergent pods made with plant-derived ingredients, gentle on clothes and the environment.',
    category: 'Home Goods',
    price: 1699,
    images: ['/laundry-pods1.png'],
    greenScore: 8,
    carbonFootprint: '0.6 kg CO₂e',
    certifications: ['Biodegradable', 'Cruelty-Free'],
    brand: 'PureCycle',
    reviews: {
      rating: 4.7,
      count: 95,
      items: [
        {
          id: 'r14',
          author: 'Priya S.',
          rating: 5,
          date: '2024-07-01',
          comment: 'My clothes come out super clean, and I love that these are eco-friendly. Great scent too!',
        },
        {
          id: 'r15',
          author: 'Rahul D.',
          rating: 4,
          date: '2024-07-05',
          comment: 'Effective detergent. The pods are convenient, but sometimes they stick together a bit.',
        },
      ],
    },
  },
  {
    id: '15',
    name: 'Recycled Paper Notebooks (3-pack)',
    description: 'Set of three notebooks with covers and pages made from 100% post-consumer recycled paper, perfect for notes and sketches.',
    category: 'Stationery',
    price: 1199,
    images: ['/recycled-notebooks1.png'],
    greenScore: 9,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['FSC Recycled'],
    brand: 'ReWrite',
    reviews: {
      rating: 4.8,
      count: 60,
      items: [
        {
          id: 'r16',
          author: 'Anjali V.',
          rating: 5,
          date: '2024-06-18',
          comment: 'Smooth paper, perfect for journaling. Feels good to be using recycled products.',
        },
      ],
    },
  },
  {
    id: '16',
    name: 'Bamboo Utensil Set with Travel Pouch',
    description: 'Lightweight and portable set of reusable bamboo fork, spoon, knife, and chopsticks, ideal for on-the-go meals.',
    category: 'Travel & Outdoors',
    price: 1299,
    images: ['/bamboo-utensil-set1.png'],
    greenScore: 10,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['BPA Free', 'Compostable'],
    brand: 'GreenGo',
    reviews: {
      rating: 4.9,
      count: 130,
      items: [
        {
          id: 'r17',
          author: 'Siddharth M.',
          rating: 5,
          date: '2024-07-10',
          comment: 'Compact and sturdy. I take this everywhere now instead of using plastic.',
        },
        {
          id: 'r18',
          author: 'Neha P.',
          rating: 4,
          date: '2024-07-15',
          comment: 'Great for lunches at work. Wish the pouch had a separate slot for each utensil.',
        },
      ],
    },
  },
  {
    id: '17',
    name: 'Organic Cotton Produce Bags (Set of 5)',
    description: 'Breathable and washable mesh bags made from 100% organic cotton, perfect for fruits and vegetables at the grocery store.',
    category: 'Kitchen & Dining',
    price: 1499,
    images: ['/cotton-produce-bags1.png',],
    greenScore: 9,
    carbonFootprint: '0.4 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'FarmToBag',
    reviews: {
      rating: 4.8,
      count: 115,
      items: [],
    },
  },
  {
    id: '18',
    name: 'Beeswax Food Wraps (Assorted 3-pack)',
    description: 'Reusable and sustainable alternative to plastic wrap, made from organic cotton infused with beeswax, jojoba oil, and tree resin.',
    category: 'Kitchen & Dining',
    price: 1999,
    images: ['/beeswax-wraps1.png'],
    greenScore: 9,
    carbonFootprint: '0.2 kg CO₂e',
    certifications: ['Biodegradable'],
    brand: 'HiveFresh',
    reviews: {
      rating: 4.6,
      count: 70,
      items: [],
    },
  },
  {
    id: '19',
    name: 'Zero-Waste Shampoo Bar',
    description: 'A solid shampoo bar made with natural ingredients, eliminates plastic bottle waste and lasts longer than liquid shampoo.',
    category: 'Personal Care',
    price: 999,
    images: ['/shampoo-bar1.png'],
    greenScore: 10,
    carbonFootprint: '0.05 kg CO₂e',
    certifications: ['Sulfate-Free', 'Plastic-Free'],
    brand: 'EcoWash',
    reviews: {
      rating: 4.5,
      count: 155,
      items: [
        {
          id: 'r19',
          author: 'Divya R.',
          rating: 5,
          date: '2024-07-20',
          comment: 'My hair feels amazing, and it lathers really well. So happy to ditch the plastic bottles!',
        },
        {
          id: 'r20',
          author: 'Arjun S.',
          rating: 4,
          date: '2024-07-22',
          comment: 'Takes a little getting used to, but it cleans effectively. Good for travel too.',
        },
      ],
    },
  },
  {
    id: '20',
    name: 'Recycled Rubber Door Mat',
    description: 'A durable and weather-resistant door mat made from 100% recycled car tires, perfect for indoor or outdoor use.',
    category: 'Home Goods',
    price: 2499,
    images: ['/recycled-door-mat1.png'],
    greenScore: 8,
    carbonFootprint: '1.8 kg CO₂e',
    certifications: ['Recycled Content'],
    brand: 'ReRubber',
    reviews: {
      rating: 4.6,
      count: 75,
      items: [
        {
          id: 'r21',
          author: 'Priya K.',
          rating: 5,
          date: '2024-07-08',
          comment: 'Very sturdy and looks great by my front door. Love that it\'s made from recycled materials.',
        },
      ],
    },
  },
  {
    id: '21',
    name: 'Compostable Dog Waste Bags (120 count)',
    description: 'Strong and leak-proof dog waste bags that are 100% compostable and biodegradable, reducing plastic pollution.',
    category: 'Pet Supplies',
    price: 1099,
    images: ['/compostable-dog-bags1.png'],
    greenScore: 10,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['Compostable', 'Biodegradable'],
    brand: 'PoochEco',
    reviews: {
      rating: 4.7,
      count: 200,
      items: [
        {
          id: 'r22',
          author: 'Sameer G.',
          rating: 5,
          date: '2024-07-11',
          comment: 'Finally, a guilt-free way to clean up after my dog! These are strong and work well.',
        },
        {
          id: 'r23',
          author: 'Rina T.',
          rating: 4,
          date: '2024-07-13',
          comment: 'Good quality bags. A little pricier than regular ones, but worth it for the environment.',
        },
      ],
    },
  },
  {
    id: '22',
    name: 'Sustainable Wood Coasters (Set of 4)',
    description: 'Hand-carved coasters made from sustainably harvested wood, naturally protecting your surfaces in style.',
    category: 'Home Decor',
    price: 1799,
    images: ['/wood-coasters1.png'],
    greenScore: 8,
    carbonFootprint: '0.5 kg CO₂e',
    certifications: ['FSC Certified Wood'],
    brand: 'ForestCraft',
    reviews: {
      rating: 4.8,
      count: 40,
      items: [],
    },
  },
  {
    id: '23',
    name: 'Upcycled Denim Pouch',
    description: 'A versatile and unique pouch made from repurposed denim, perfect for stationery, cosmetics, or small essentials.',
    category: 'Accessories',
    price: 1599,
    images: ['/upcycled-denim-pouch1.png'],
    greenScore: 9,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'ReFashion',
    reviews: {
      rating: 4.9,
      count: 30,
      items: [],
    },
  },
   {
    id: '24',
    name: 'Biodegradable Glitter (Eco-friendly)',
    description: 'Sparkling guilt-free! This glitter is made from plant-derived materials and is certified biodegradable, safe for you and the planet.',
    category: 'Craft Supplies',
    price: 699,
    images: ['/biodegradable-glitter1.png'],
    greenScore: 9,
    carbonFootprint: '0.01 kg CO₂e',
    certifications: ['Biodegradable', 'Cosmetic Grade'],
    brand: 'EcoShine',
    reviews: {
      rating: 4.5,
      count: 88,
      items: [
        {
          id: 'r24',
          author: 'Pooja K.',
          rating: 5,
          date: '2024-06-25',
          comment: 'Perfect for my art projects! It sparkles beautifully and washes away without guilt.',
        },
        {
          id: 'r25',
          author: 'Kabir S.',
          rating: 4,
          date: '2024-06-28',
          comment: 'Great product, but the container is a bit small for the price.',
        },
      ],
    },
  },
  {
    id: '25',
    name: 'Recycled Plastic Planters (Set of 3)',
    description: 'Lightweight and durable planters made from 100% recycled plastic, perfect for indoor or outdoor gardening.',
    category: 'Outdoor & Garden',
    price: 2999,
    images: ['/recycled-planters1.png',],
    greenScore: 8,
    carbonFootprint: '1.2 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'GreenGrow',
    reviews: {
      rating: 4.7,
      count: 55,
      items: [],
    },
  },
  {
    id: '26',
    name: 'Organic Cotton Baby Bodysuit',
    description: 'Supersoft and breathable bodysuit for babies, made from 100% organic cotton, gentle on delicate skin.',
    category: 'Baby & Kids',
    price: 1599,
    images: ['/organic-baby-bodysuit1.png',],
    greenScore: 9,
    carbonFootprint: '0.2 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'LittleEco',
    reviews: {
      rating: 4.9,
      count: 105,
      items: [
        {
          id: 'r26',
          author: 'Neha C.',
          rating: 5,
          date: '2024-07-01',
          comment: 'So soft for my little one! I love knowing it\'s organic and safe.',
        },
        {
          id: 'r27',
          author: 'Aarav G.',
          rating: 5,
          date: '2024-07-03',
          comment: 'Excellent quality and fits well. Will definitely buy more.',
        },
      ],
    },
  },
  {
    id: '27',
    name: 'Reusable Coffee Cup (Bamboo Fiber)',
    description: 'A stylish and lightweight reusable coffee cup made from sustainable bamboo fiber, with a silicone lid.',
    category: 'Kitchen & Dining',
    price: 1399,
    images: ['/bamboo-coffee-cup1.png'],
    greenScore: 8,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['BPA Free'],
    brand: 'SipEco',
    reviews: {
      rating: 4.6,
      count: 160,
      items: [],
    },
  },
  {
    id: '28',
    name: 'Natural Loofah Sponge (Biodegradable)',
    description: 'A 100% natural and biodegradable exfoliating sponge, perfect for a refreshing shower or bath.',
    category: 'Personal Care',
    price: 499,
    images: ['/natural-loofah1.png'],
    greenScore: 10,
    carbonFootprint: '0.02 kg CO₂e',
    certifications: ['Compostable'],
    brand: 'PureScrub',
    reviews: {
      rating: 4.7,
      count: 90,
      items: [],
    },
  },
  {
    id: '29',
    name: 'Recycled Glass Vases (Set of 2)',
    description: 'Elegant and unique vases made from upcycled glass bottles, adding a touch of eco-conscious style to your home.',
    category: 'Home Decor',
    price: 2699,
    images: ['/recycled-vases1.png'],
    greenScore: 8,
    carbonFootprint: '1.0 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'ReBloom',
    reviews: {
      rating: 4.8,
      count: 38,
      items: [],
    },
  },
  {
    id: '30',
    name: 'Solid Dish Soap Bar',
    description: 'An effective and long-lasting alternative to liquid dish soap, cuts grease and eliminates plastic bottle waste.',
    category: 'Home Goods',
    price: 799,
    images: ['/dish-soap-bar1.png'],
    greenScore: 10,
    carbonFootprint: '0.08 kg CO₂e',
    certifications: ['Palm Oil Free', 'Plastic-Free'],
    brand: 'SparkleBar',
    reviews: {
      rating: 4.6,
      count: 110,
      items: [
        {
          id: 'r28',
          author: 'Deepika S.',
          rating: 5,
          date: '2024-07-18',
          comment: 'Works wonders on greasy dishes! And no more plastic bottles cluttering my sink.',
        },
      ],
    },
  },
  {
    id: '31',
    name: 'Organic Cotton Kitchen Towels (Set of 3)',
    description: 'Highly absorbent and durable kitchen towels made from 100% organic cotton, a sustainable choice for your home.',
    category: 'Kitchen & Dining',
    price: 1899,
    images: ['/cotton-kitchen-towels1.png'],
    greenScore: 9,
    carbonFootprint: '0.5 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'PureWipe',
    reviews: {
      rating: 4.7,
      count: 80,
      items: [],
    },
  },
  {
    id: '32',
    name: 'Stainless Steel Lunch Box (Stackable)',
    description: 'A multi-tier, leak-proof lunch box made from food-grade stainless steel, perfect for packing waste-free meals.',
    category: 'Kitchen & Dining',
    price: 2799,
    images: ['/stainless-lunch-box1.png'],
    greenScore: 8,
    carbonFootprint: '0.9 kg CO₂e',
    certifications: ['BPA Free'],
    brand: 'EcoCarry',
    reviews: {
      rating: 4.9,
      count: 140,
      items: [
        {
          id: 'r29',
          author: 'Vikram A.',
          rating: 5,
          date: '2024-07-20',
          comment: 'Perfect for my daily lunch! Keeps food fresh and I love the stackable design.',
        },
      ],
    },
  },
  {
    id: '33',
    name: 'Recycled Glass Candle Holder',
    description: 'A charming candle holder crafted from recycled glass, creating a beautiful ambiance with a sustainable touch.',
    category: 'Home Decor',
    price: 1199,
    images: ['/recycled-candle-holder1.png'],
    greenScore: 7,
    carbonFootprint: '0.4 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'GlowGreen',
    reviews: {
      rating: 4.5,
      count: 50,
      items: [],
    },
  },
  {
    id: '34',
    name: 'Bamboo Hair Brush',
    description: 'A gentle and eco-friendly hair brush with a bamboo handle and natural bristles, reduces static and promotes healthy hair.',
    category: 'Personal Care',
    price: 1299,
    images: ['/bamboo-hair-brush1.png'],
    greenScore: 9,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'NatureTress',
    reviews: {
      rating: 4.7,
      count: 65,
      items: [],
    },
  },
  {
    id: '35',
    name: 'Compostable Snack Bags (Reusable, Set of 4)',
    description: 'A convenient and eco-conscious way to store snacks. These bags are made from plant-based materials and are fully compostable.',
    category: 'Kitchen & Dining',
    price: 999,
    images: ['/compostable-snack-bags1.png'],
    greenScore: 10,
    carbonFootprint: '0.05 kg CO₂e',
    certifications: ['Compostable', 'Reusable'],
    brand: 'SnackEco',
    reviews: {
      rating: 4.6,
      count: 70,
      items: [],
    },
  },
  {
    id: '36',
    name: 'Organic Cotton Tote Bag',
    description: 'A spacious and durable tote bag made from 100% organic cotton, perfect for groceries, books, or everyday use.',
    category: 'Accessories',
    price: 1699,
    images: ['/organic-tote-bag1.png'],
    greenScore: 9,
    carbonFootprint: '0.6 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'CarryPure',
    reviews: {
      rating: 4.9,
      count: 220,
      items: [
        {
          id: 'r30',
          author: 'Aditi V.',
          rating: 5,
          date: '2024-07-15',
          comment: 'My go-to bag for everything! Strong, stylish, and ethical.',
        },
      ],
    },
  },
  {
    id: '37',
    name: 'Upcycled Fabric Journal',
    description: 'A unique journal with a cover made from upcycled fabric scraps, each one a one-of-a-kind piece.',
    category: 'Stationery',
    price: 1499,
    images: ['/upcycled-journal1.png'],
    greenScore: 8,
    carbonFootprint: '0.2 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'PatchWorks',
    reviews: {
      rating: 4.7,
      count: 45,
      items: [],
    },
  },
  {
    id: '38',
    name: 'Bamboo Clothes Pegs (40 count)',
    description: 'Durable and natural clothes pegs made from sustainably sourced bamboo, a plastic-free alternative for your laundry.',
    category: 'Laundry',
    price: 899,
    images: ['/bamboo-clothes-pegs1.png'],
    greenScore: 10,
    carbonFootprint: '0.08 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'PegEco',
    reviews: {
      rating: 4.8,
      count: 70,
      items: [],
    },
  },
  {
    id: '39',
    name: 'Recycled Cardboard Cat Scratcher',
    description: 'A robust and eco-friendly cat scratcher made from recycled cardboard, satisfying your cat\'s natural instincts.',
    category: 'Pet Supplies',
    price: 1999,
    images: ['/recycled-cat-scratcher1.png'],
    greenScore: 7,
    carbonFootprint: '0.7 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'PawsomeEco',
    reviews: {
      rating: 4.5,
      count: 50,
      items: [],
    },
  },
  {
    id: '40',
    name: 'Natural Konjac Facial Sponge',
    description: 'A gentle and biodegradable facial cleansing sponge made from the Konjac plant, perfect for all skin types.',
    category: 'Personal Care',
    price: 599,
    images: ['/konjac-sponge1.png'],
    greenScore: 10,
    carbonFootprint: '0.03 kg CO₂e',
    certifications: ['Compostable'],
    brand: 'BloomSkin',
    reviews: {
      rating: 4.8,
      count: 100,
      items: [
        {
          id: 'r31',
          author: 'Sneha P.',
          rating: 5,
          date: '2024-07-22',
          comment: 'My skin has never felt softer! It\'s so gentle and I love that it\'s natural.',
        },
      ],
    },
  },
  {
    id: '41',
    name: 'Solar-Powered Backpack',
    description: 'A multi-functional backpack with an integrated solar panel, allowing you to charge your devices on the go.',
    category: 'Electronics Accessories',
    price: 8999,
    images: ['/solar-backpack1.png',],
    greenScore: 8,
    carbonFootprint: '3.5 kg CO₂e',
    certifications: ['Renewable Energy'],
    brand: 'SunTrek',
    reviews: {
      rating: 4.6,
      count: 25,
      items: [],
    },
  },
  {
    id: '42',
    name: 'Organic Cotton Swabs (Paper Sticks, 200 count)',
    description: 'Biodegradable cotton swabs with strong paper sticks, a sustainable alternative to plastic cotton swabs.',
    category: 'Personal Care',
    price: 499,
    images: ['/organic-cotton-swabs1.png'],
    greenScore: 10,
    carbonFootprint: '0.01 kg CO₂e',
    certifications: ['Biodegradable', 'GOTS'],
    brand: 'PureBuds',
    reviews: {
      rating: 4.7,
      count: 120,
      items: [],
    },
  },
  {
    id: '43',
    name: 'Bamboo Dish Brush with Replaceable Head',
    description: 'An ergonomic dish brush with a bamboo handle and a replaceable head, reducing plastic waste in your kitchen.',
    category: 'Home Goods',
    price: 999,
    images: ['/bamboo-dish-brush1.png'],
    greenScore: 9,
    carbonFootprint: '0.07 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'ScrubEco',
    reviews: {
      rating: 4.6,
      count: 85,
      items: [],
    },
  },
  {
    id: '44',
    name: 'Compostable Cling Wrap Alternative',
    description: 'A plant-based, breathable wrap that is fully compostable, offering a sustainable way to keep food fresh.',
    category: 'Kitchen & Dining',
    price: 1199,
    images: ['/compostable-cling-wrap1.png'],
    greenScore: 10,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['Compostable'],
    brand: 'FreshCycle',
    reviews: {
      rating: 4.5,
      count: 60,
      items: [],
    },
  },
  {
    id: '45',
    name: 'Recycled Glass Tumbler with Lid & Straw',
    description: 'A stylish and practical tumbler made from 100% recycled glass, complete with a bamboo lid and reusable straw.',
    category: 'Kitchen & Dining',
    price: 1699,
    images: ['/recycled-glass-tumbler-straw1.png'],
    greenScore: 9,
    carbonFootprint: '0.6 kg CO₂e',
    certifications: ['Recycled', 'BPA Free'],
    brand: 'GreenSip',
    reviews: {
      rating: 4.8,
      count: 95,
      items: [],
    },
  },
  {
    id: '46',
    name: 'Bamboo Bath Mat',
    description: 'A quick-drying and naturally antimicrobial bath mat made from sustainable bamboo, adds a spa-like feel to your bathroom.',
    category: 'Home Goods',
    price: 2299,
    images: ['/bamboo-bath-mat1.png'],
    greenScore: 8,
    carbonFootprint: '0.8 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'ZenLiving',
    reviews: {
      rating: 4.7,
      count: 50,
      items: [],
    },
  },
  {
    id: '47',
    name: 'Organic Cotton Scrubber Sponges (2-pack)',
    description: 'Durable and gentle scrubber sponges made from organic cotton and natural plant fibers, ideal for non-stick surfaces.',
    category: 'Home Goods',
    price: 899,
    images: ['/organic-scrubber-sponges1.png'],
    greenScore: 9,
    carbonFootprint: '0.15 kg CO₂e',
    certifications: ['GOTS', 'Biodegradable'],
    brand: 'CleanGreen',
    reviews: {
      rating: 4.6,
      count: 75,
      items: [],
    },
  },
  {
    id: '48',
    name: 'Upcycled Denim Potholders (Set of 2)',
    description: 'Unique and heat-resistant potholders crafted from repurposed denim, adding a rustic and sustainable touch to your kitchen.',
    category: 'Kitchen & Dining',
    price: 1099,
    images: ['/upcycled-denim-potholders1.png'],
    greenScore: 8,
    carbonFootprint: '0.2 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'ReStitch',
    reviews: {
      rating: 4.7,
      count: 35,
      items: [],
    },
  },
  {
    id: '49',
    name: 'Plant-Based Laundry Stain Remover',
    description: 'An effective and eco-friendly stain remover made with powerful plant-derived enzymes, tough on stains, gentle on fabrics.',
    category: 'Laundry',
    price: 999,
    images: ['/plant-stain-remover1.png'],
    greenScore: 9,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['Biodegradable', 'Vegan'],
    brand: 'SpotlessEco',
    reviews: {
      rating: 4.5,
      count: 60,
      items: [],
    },
  },
  {
    id: '50',
    name: 'Bamboo Pen Set (Refillable)',
    description: 'A sleek and sustainable pen set made from bamboo with refillable ink cartridges, reducing plastic waste from disposables.',
    category: 'Stationery',
    price: 1399,
    images: ['/bamboo-pen-set1.png'],
    greenScore: 9,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'WriteGreen',
    reviews: {
      rating: 4.8,
      count: 40,
      items: [],
    },
  },
  {
    id: '51',
    name: 'Recycled Ocean Plastic Keychain',
    description: 'A meaningful keychain made from plastic collected from ocean clean-up efforts, a small reminder of big impact.',
    category: 'Accessories',
    price: 199,
    images: ['/ocean-plastic-keychain1.png'],
    greenScore: 10,
    carbonFootprint: '0.05 kg CO₂e',
    certifications: ['Ocean Plastic'],
    brand: 'SeaCycle',
    reviews: {
      rating: 5.0,
      count: 90,
      items: [],
    },
  },
  {
    id: '52',
    name: 'Organic Cotton Produce Bags (Mesh, Small)',
    description: 'A smaller, breathable mesh bag made from 100% organic cotton, perfect for delicate produce like mushrooms or berries.',
    category: 'Kitchen & Dining',
    price: 699,
    images: ['/cotton-produce-bag-small1.png'],
    greenScore: 9,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'FarmToBag',
    reviews: {
      rating: 4.8,
      count: 65,
      items: [],
    },
  },
  {
    id: '53',
    name: 'Rechargeable LED Headlamp',
    description: 'An energy-efficient and durable headlamp with a long-lasting rechargeable battery, ideal for outdoor adventures.',
    category: 'Outdoor & Garden',
    price: 2999,
    images: ['/rechargeable-headlamp1.png'],
    greenScore: 8,
    carbonFootprint: '0.8 kg CO₂e',
    certifications: ['Energy Efficient'],
    brand: 'BrightEco',
    reviews: {
      rating: 4.7,
      count: 45,
      items: [],
    },
  },
   {
    id: '54',
    name: 'Biodegradable Face Wipes (60 count)',
    description: 'Gentle and effective face wipes made from 100% plant-based fibers, fully biodegradable and compostable.',
    category: 'Personal Care',
    price: 899,
    images: ['/biodegradable-face-wipes1.png'],
    greenScore: 9,
    carbonFootprint: '0.05 kg CO₂e',
    certifications: ['Compostable', 'Vegan'],
    brand: 'CleanGlow',
    reviews: {
      rating: 4.6,
      count: 110,
      items: [
        {
          id: 'r32',
          author: 'Meena K.',
          rating: 5,
          date: '2024-07-25',
          comment: 'Love these! They remove makeup effectively and I feel good knowing they break down naturally.',
        },
      ],
    },
  },
  {
    id: '55',
    name: 'Recycled Aluminum Foil (75 sq ft)',
    description: 'A sustainable alternative for your kitchen, this aluminum foil is made from 100% recycled content and is endlessly recyclable.',
    category: 'Kitchen & Dining',
    price: 699,
    images: ['/recycled-foil1.png'],
    greenScore: 8,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['Recycled Content'],
    brand: 'ReWrap',
    reviews: {
      rating: 4.5,
      count: 80,
      items: [],
    },
  },
  {
    id: '56',
    name: 'Organic Cotton Produce Bags (Drawstring, Large)',
    description: 'Large, durable, and breathable produce bags with a drawstring closure, made from 100% organic cotton.',
    category: 'Kitchen & Dining',
    price: 999,
    images: ['/cotton-produce-bag-large1.png'],
    greenScore: 9,
    carbonFootprint: '0.2 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'FarmToBag',
    reviews: {
      rating: 4.9,
      count: 130,
      items: [],
    },
  },
  {
    id: '57',
    name: 'Bamboo Paper Towels (Reusable, 2-roll pack)',
    description: 'Ultra-absorbent and durable paper towels made from sustainable bamboo, washable and reusable for up to 100 uses per sheet.',
    category: 'Home Goods',
    price: 1599,
    images: ['/bamboo-paper-towels1.png'],
    greenScore: 10,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'EcoWipe',
    reviews: {
      rating: 4.7,
      count: 90,
      items: [
        {
          id: 'r33',
          author: 'Kunal D.',
          rating: 5,
          date: '2024-07-20',
          comment: 'These are amazing! Super absorbent and I love that I can just wash and reuse them. A great way to save money and the environment.',
        },
      ],
    },
  },
  {
    id: '58',
    name: 'Stainless Steel Ice Cubes (Set of 8)',
    description: 'Reusable and food-grade stainless steel ice cubes that chill your drinks without diluting them, comes with a velvet storage bag.',
    category: 'Kitchen & Dining',
    price: 1299,
    images: ['/stainless-steel-ice-cubes1.png'],
    greenScore: 8,
    carbonFootprint: '0.4 kg CO₂e',
    certifications: ['Food Grade'],
    brand: 'ChillEco',
    reviews: {
      rating: 4.6,
      count: 100,
      items: [],
    },
  },
  {
    id: '59',
    name: 'Compostable Garbage Bags (13 Gallon, 20 count)',
    description: 'Strong and tear-resistant garbage bags made from plant-based materials, fully compostable in commercial composting facilities.',
    category: 'Home Goods',
    price: 1099,
    images: ['/compostable-garbage-bags1.png'],
    greenScore: 9,
    carbonFootprint: '0.5 kg CO₂e',
    certifications: ['Compostable'],
    brand: 'BioBag',
    reviews: {
      rating: 4.4,
      count: 70,
      items: [],
    },
  },
  {
    id: '60',
    name: 'Upcycled Book End (Single)',
    description: 'A unique and sturdy book end crafted from salvaged wood or metal, each piece is individually designed and tells a story.',
    category: 'Home Decor',
    price: 1999,
    images: ['/upcycled-book-end1.png'],
    greenScore: 8,
    carbonFootprint: '0.7 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'RePurposeDecor',
    reviews: {
      rating: 4.8,
      count: 25,
      items: [],
    },
  },
  {
    id: '61',
    name: 'Natural Bristle Cleaning Brush (Wooden Handle)',
    description: 'An effective and plastic-free cleaning brush with durable natural bristles and a comfortable wooden handle, perfect for scrubbing surfaces.',
    category: 'Home Goods',
    price: 799,
    images: ['/natural-cleaning-brush1.png'],
    greenScore: 9,
    carbonFootprint: '0.09 kg CO₂e',
    certifications: ['Biodegradable'],
    brand: 'CleanSweep',
    reviews: {
      rating: 4.7,
      count: 60,
      items: [],
    },
  },
  {
    id: '62',
    name: 'Organic Cotton Mesh Bag (Small)',
    description: 'A small, breathable mesh bag made from 100% organic cotton, perfect for storing nuts, herbs, or small produce.',
    category: 'Kitchen & Dining',
    price: 599,
    images: ['/cotton-mesh-bag-small1.png'],
    greenScore: 9,
    carbonFootprint: '0.08 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'FarmToBag',
    reviews: {
      rating: 4.8,
      count: 55,
      items: [],
    },
  },
  {
    id: '63',
    name: 'Recycled Denim Coasters (Set of 4)',
    description: 'Stylish and absorbent coasters made from upcycled denim, protecting your surfaces with a unique touch.',
    category: 'Home Decor',
    price: 1299,
    images: ['/recycled-denim-coasters1.png'],
    greenScore: 8,
    carbonFootprint: '0.25 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'ReJeanHome',
    reviews: {
      rating: 4.6,
      count: 40,
      items: [],
    },
  },
  {
    id: '64',
    name: 'Bamboo Travel Utensil Set (Kid-friendly)',
    description: 'A smaller, child-sized set of reusable bamboo fork, spoon, and knife with a fun travel pouch, encouraging eco-habits early.',
    category: 'Baby & Kids',
    price: 1099,
    images: ['/bamboo-kid-utensil-set1.png'],
    greenScore: 10,
    carbonFootprint: '0.07 kg CO₂e',
    certifications: ['BPA Free', 'Compostable'],
    brand: 'GreenGoKids',
    reviews: {
      rating: 4.9,
      count: 80,
      items: [
        {
          id: 'r34',
          author: 'Priyanka N.',
          rating: 5,
          date: '2024-07-24',
          comment: 'Perfect for my toddler! She loves her "special" utensils, and I love that they\'re not plastic.',
        },
      ],
    },
  },
  {
    id: '65',
    name: 'Solar-Powered Power Bank',
    description: 'A portable power bank that charges via solar energy, providing a convenient and eco-friendly way to power your devices on the go.',
    category: 'Electronics Accessories',
    price: 3499,
    images: ['/solar-power-bank1.png'],
    greenScore: 8,
    carbonFootprint: '1.5 kg CO₂e',
    certifications: ['Renewable Energy'],
    brand: 'SunCharge',
    reviews: {
      rating: 4.6,
      count: 50,
      items: [],
    },
  },
  {
    id: '66',
    name: 'Compostable Coffee Pods (Nespresso Compatible, 10 count)',
    description: 'Enjoy your coffee guilt-free with these fully compostable coffee pods, compatible with Nespresso machines.',
    category: 'Food & Beverage',
    price: 799,
    images: ['/compostable-coffee-pods1.png'],
    greenScore: 9,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['Compostable'],
    brand: 'BeanGreen',
    reviews: {
      rating: 4.4,
      count: 90,
      items: [],
    },
  },
  {
    id: '67',
    name: 'Organic Cotton Baby Blanket',
    description: 'A soft and breathable blanket for babies, made from 100% organic cotton, perfect for sensitive skin and cozy cuddles.',
    category: 'Baby & Kids',
    price: 2999,
    images: ['/organic-baby-blanket1.png'],
    greenScore: 9,
    carbonFootprint: '0.6 kg CO₂e',
    certifications: ['GOTS'],
    brand: 'LittleEco',
    reviews: {
      rating: 4.9,
      count: 70,
      items: [],
    },
  },
  {
    id: '68',
    name: 'Recycled Rubber Coasters (Set of 4)',
    description: 'Durable and non-slip coasters made from recycled rubber, a practical and eco-conscious addition to your home.',
    category: 'Home Decor',
    price: 999,
    images: ['/recycled-rubber-coasters1.png'],
    greenScore: 8,
    carbonFootprint: '0.3 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'ReRubberHome',
    reviews: {
      rating: 4.5,
      count: 30,
      items: [],
    },
  },
];

export const categories = [
  { name: 'All', value: 'all' },
  { name: 'Apparel', value: 'apparel' },
  { name: 'Home Goods', value: 'home-goods' },
  { name: 'Personal Care', value: 'personal-care' },
  { name: 'Accessories', value: 'accessories' },
  { name: 'Fitness', value: 'fitness' },
];

export const brands = [
  { name: 'All Brands', value: 'all' },
  { name: 'EcoThreads', value: 'ecothreads' },
  { name: 'GreenGlass', value: 'greenglass' },
  { name: 'NatureBrush', value: 'naturebrush' },
  { name: 'AuraScents', value: 'aurascents' },
  { name: 'CarryGreen', value: 'carrygreen' },
  { name: 'HempWorks', value: 'hempworks' },
  { name: 'ReJean', value: 'rejean' },
  { name: 'ZenCork', value: 'zencork' },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: '10 Simple Swaps for a More Sustainable Kitchen',
    description: 'Discover easy-to-implement changes that can make your kitchen more eco-friendly, from reusable wraps to composting tips.',
    content: [
      "The kitchen is often called the heart of the home, but it can also be a major source of waste. From single-use plastics to food scraps, the environmental footprint of our kitchens can be significant. The good news is that making a positive change is easier than you think! By swapping out a few everyday items for more sustainable alternatives, you can drastically reduce your waste and create a healthier home and planet.",
      "Here are 10 simple swaps to get you started on your journey to a zero-waste kitchen:",
      "1. Ditch Plastic Wrap for Beeswax Wraps: A natural, reusable, and biodegradable alternative to cling film. They're perfect for covering bowls, wrapping sandwiches, or storing leftover vegetables.",
      "2. Switch to Reusable Produce Bags: Say goodbye to flimsy plastic produce bags at the grocery store. Cloth or mesh bags are durable, washable, and prevent countless plastic bags from ending up in landfills.",
      "3. Embrace the Swedish Dishcloth: These amazing cloths, made from cellulose and cotton, are super absorbent and can replace up to 17 rolls of paper towels. They can be washed and reused for months.",
      "4. Start a Compost Bin: Don't throw away valuable food scraps! Composting fruit and vegetable peels, coffee grounds, and eggshells enriches soil and reduces the amount of waste sent to the landfill, where it would otherwise produce methane gas.",
      "5. Use Glass Storage Containers: Instead of plastic Tupperware that can stain and warp, invest in a set of glass containers. They're durable, non-toxic, and can go from the freezer to the microwave or oven without any issues.",
      "6. Brew Coffee Sustainably: If you're a coffee lover, consider a French press, pour-over, or reusable coffee pods instead of single-use filters or K-cups.",
      "7. Make Your Own Cleaning Supplies: A simple mixture of vinegar, water, and essential oils in a reusable spray bottle can tackle most cleaning jobs, eliminating the need for harsh chemicals and plastic bottles.",
      "8. Buy in Bulk: The bulk section of your grocery store is your best friend. Bring your own jars and containers to stock up on grains, nuts, spices, and oils, significantly reducing packaging waste.",
      "9. Choose a Bamboo Dish Brush: A bamboo brush with natural fiber bristles is a fantastic, biodegradable alternative to plastic dish sponges, which shed microplastics into our waterways.",
      "10. Grow Your Own Herbs: A small herb garden on your windowsill not only provides fresh ingredients for your meals but also eliminates the plastic packaging that fresh herbs typically come in.",
      "Making these small changes can add up to a big impact. Start with one or two swaps and see how easy it is to build a more sustainable kitchen and lifestyle."
    ],
    category: 'Tips & Tricks',
    date: 'April 22, 2024',
    image: '/blog-image1.png',
    dataAiHint: 'sustainable kitchen',
    comments: [
        { id: 'c1', author: 'EcoWarrior', comment: 'Great tips! I already use beeswax wraps, but I\'m going to start composting now.', date: '2024-04-23' },
        { id: 'c2', author: 'Sustainable Sam', comment: 'Loved this article. Another tip is to use veggie scraps to make broth!', date: '2024-04-24' },
    ],
  },
  {
    id: 2,
    title: 'The Ultimate Guide to Ethical Fashion',
    description: 'Learn what to look for when shopping for clothes to ensure your wardrobe is as kind to the planet as it is to people.',
    content: [
      "In a world of fast fashion, building a wardrobe that aligns with your values can feel like a daunting task. But what exactly is 'ethical fashion'? It's a broad term that encompasses a focus on environmental sustainability, animal welfare, and social responsibility for the people who make our clothes. It's about choosing quality over quantity and supporting brands that are transparent about their practices.",
      "Navigating the world of sustainable style is much easier when you know what to look for. Here's our guide to making more conscious fashion choices:",
      "1. Understand the Materials: The fabric of your clothes is the first step. Look for natural, low-impact fibers like Organic Cotton (uses less water and no pesticides), Linen (durable and made from the flax plant), Hemp (requires very little water and regenerates soil), and TENCEL™ Lyocell (made from sustainably sourced wood pulp in a closed-loop system). Avoid synthetic materials like polyester and nylon when possible, as they are derived from fossil fuels and shed microplastics when washed.",
      "2. Look for Certifications: Certifications are a great way to verify a brand's claims. Keep an eye out for labels like GOTS (Global Organic Textile Standard) for organic materials, Fair Trade Certified to ensure workers are paid fair wages and have safe working conditions, and B Corp, which signifies a company meets high standards of social and environmental performance, accountability, and transparency.",
      "3. Embrace Secondhand and Vintage: The most sustainable item is the one that already exists! Thrifting, consignment shopping, and clothing swaps are fantastic ways to give garments a second life, reduce waste, and find unique pieces that express your personal style.",
      "4. Prioritize Quality and Longevity: Fast fashion is designed to be disposable. Ethical fashion is the opposite. Invest in well-made, timeless pieces that you will love and wear for years to come. Check the stitching, the fabric quality, and the overall construction of a garment before you buy.",
      "5. Care for Your Clothes: Extend the life of your wardrobe by washing clothes less often, using cold water, and air-drying them. Learning basic mending skills, like sewing on a button or patching a small hole, can also make a huge difference.",
      "By making thoughtful choices, you can create a wardrobe that not only looks good but also does good. Your purchasing power is a vote for the kind of world you want to live in—one where fashion is fair, sustainable, and beautiful for everyone."
    ],
    category: 'Ethical Fashion',
    date: 'April 15, 2024',
    image: '/blog-image2.png',
    dataAiHint: 'ethical fashion',
    comments: [
        { id: 'c3', author: 'Fashionista', comment: 'This was so informative. I had no idea about some of these certifications.', date: '2024-04-16' },
    ],
  },
  {
    id: 3,
    title: 'Brand Spotlight: The Story Behind EcoThreads',
    description: 'Go behind the scenes with the founders of EcoThreads and learn about their mission to create stylish, sustainable apparel.',
    content: [
      "At AuraGrove, we're proud to partner with brands that share our commitment to sustainability and ethical practices. Today, we're thrilled to shine a spotlight on one of our favorite apparel brands: EcoThreads. More than just a clothing line, EcoThreads is a movement dedicated to proving that style and sustainability can, and should, go hand in hand.",
      "EcoThreads was founded by lifelong friends Maya and Liam, who were disillusioned with the environmental and social impact of the fast fashion industry. 'We saw a gap in the market,' says Maya. 'People wanted beautiful, modern clothing, but they were also becoming more aware of the cost—not just the price tag, but the cost to the planet and the people making the garments.'",
      "Their mission was simple but ambitious: to create a collection of wardrobe essentials that were ethically made, environmentally friendly, and built to last. They started with their signature product, the Organic Cotton T-Shirt, a piece that perfectly embodies their philosophy.",
      "The journey began with sourcing the right materials. 'We spent months researching and visiting suppliers,' Liam explains. 'It was crucial for us to use 100% GOTS certified organic cotton. This ensures that the cotton is grown without harmful pesticides and with significantly less water than conventional cotton. It's better for the farmers, the environment, and for the person wearing the shirt.'",
      "But their commitment didn't stop with the fabric. They partnered with a Fair Trade certified factory in India to produce their garments. This partnership guarantees that every worker involved in making an EcoThreads product is treated with respect, paid a living wage, and works in a safe, healthy environment. 'For us, sustainability is about the entire supply chain,' Maya emphasizes. 'It's a holistic approach.'",
      "From their dyeing process, which uses non-toxic, low-impact dyes, to their plastic-free packaging, every detail is carefully considered. The result is a collection of timeless pieces that feel as good as they look. 'We want our customers to feel a connection to their clothes,' Liam says. 'To know the story behind them and to feel proud of the choice they've made.'",
      "EcoThreads is a testament to the power of conscious consumerism and the positive change that purpose-driven brands can create. We are honored to feature them at AuraGrove and to be a part of their journey toward a more beautiful and sustainable future."
    ],
    category: 'Brand Spotlight',
    date: 'April 8, 2024',
    image: '/blog-image3.png',
    dataAiHint: 'fashion brand',
    comments: [],
  },
];

export const forumPosts: ForumPost[] = [
  {
    id: 'fp1',
    title: 'What are your favorite zero-waste cleaning hacks?',
    author: 'EcoWarrior',
    date: '2024-05-20',
    content: 'I\'m trying to reduce the number of plastic bottles under my sink. I\'ve started using a vinegar and water solution for surfaces, but what do you all use for things like tubs and toilets? Looking for some effective, DIY recipes!',
    replies: [
      { id: 'fr1', author: 'Sustainable Sam', date: '2024-05-20', content: 'Baking soda is my go-to! A paste of baking soda and water works wonders on tubs. For toilets, I just sprinkle some in, add a bit of vinegar, let it fizz, and then scrub.' },
      { id: 'fr2', author: 'Green Thumb', date: '2024-05-21', content: 'I love using citrus peels! I soak lemon and orange peels in vinegar for a couple of weeks. It makes a great all-purpose cleaner that smells amazing and cuts through grease.' },
    ],
  },
  {
    id: 'fp2',
    title: 'Best sustainable documentaries to watch?',
    author: 'MovieBuff',
    date: '2024-05-18',
    content: 'Hey everyone, I\'m looking for some inspiring and informative documentaries about sustainability, ethical living, and environmental issues. What are some must-sees that have really impacted you?',
    replies: [
      { id: 'fr3', author: 'Jane D.', date: '2024-05-18', content: '"The True Cost" is a must-watch if you\'re interested in the fashion industry. It completely changed the way I shop for clothes.' },
      { id: 'fr4', author: 'EcoWarrior', date: '2024-05-19', content: 'I second "The True Cost"! Also, "Kiss the Ground" on Netflix is a fantastic and hopeful film about regenerative agriculture.' },
      { id: 'fr5', author: 'Tom W.', date: '2024-05-19', content: '"My Octopus Teacher" isn\'t strictly about sustainability, but it gives you such a profound connection to the natural world. Highly recommend.' },
    ],
  },
  {
    id: 'fp3',
    title: 'Tips for reducing food waste?',
    author: 'Chef Charlie',
    date: '2024-05-15',
    content: 'As someone who loves to cook, I hate seeing food go to waste. Beyond just composting, what are some creative ways you all use up food scraps or leftovers? I\'m trying to get better at meal planning, but any other tips would be awesome.',
    replies: [],
  },
];
