import type { Product, BlogPost } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Cotton T-Shirt',
    description: 'A soft, comfortable t-shirt made from 100% organic cotton, grown without harmful pesticides.',
    category: 'Apparel',
    price: 1999,
    images: ['https://placehold.co/1200x675.png', 'https://placehold.co/1200x675.png', 'https://placehold.co/1200x675.png'],
    greenScore: 9,
    carbonFootprint: '2.1 kg CO₂e',
    certifications: ['GOTS', 'Fair Trade'],
    brand: 'EcoThreads',
    reviews: {
      rating: 4.8,
      count: 120,
      items: [
        { id: 'r1', author: 'Jane D.', rating: 5, date: '2024-05-10', comment: 'Incredibly soft and fits perfectly. You can feel the quality. Worth every penny!' },
        { id: 'r2', author: 'Mike P.', rating: 4, date: '2024-05-12', comment: 'Great t-shirt, very comfortable. I wish it came in more colors though.' },
        { id: 'r3', author: 'Sarah K.', rating: 5, date: '2024-05-15', comment: 'My new favorite shirt. I love that it\'s ethically made.' },
      ],
    },
  },
  {
    id: '2',
    name: 'Recycled Glass Tumblers',
    description: 'Set of four drinking glasses made from 100% recycled glass, perfect for any beverage.',
    category: 'Home Goods',
    price: 2999,
    images: ['https://placehold.co/1200x675.png', 'https://placehold.co/1200x675.png'],
    greenScore: 8,
    carbonFootprint: '1.5 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'GreenGlass',
    reviews: {
      rating: 4.9,
      count: 85,
      items: [
        { id: 'r4', author: 'Tom W.', rating: 5, date: '2024-04-20', comment: 'These glasses are beautiful and have a nice weight to them. Very high quality.' },
        { id: 'r5', author: 'Emily R.', rating: 5, date: '2024-04-25', comment: 'I love the subtle green tint. They look great in my kitchen.' },
      ],
    },
  },
  {
    id: '3',
    name: 'Bamboo Toothbrush Set',
    description: 'A pack of four biodegradable toothbrushes with handles made from sustainably sourced bamboo.',
    category: 'Personal Care',
    price: 999,
    images: ['https://placehold.co/1200x675.png', 'https://placehold.co/1200x675.png'],
    greenScore: 10,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'NatureBrush',
    reviews: {
      rating: 4.7,
      count: 213,
      items: [
        { id: 'r6', author: 'David L.', rating: 5, date: '2024-05-01', comment: 'Good for my teeth and good for the planet. Makes me happy.' },
        { id: 'r7', author: 'Jessica M.', rating: 4, date: '2024-05-05', comment: 'The bristles are a bit softer than I expected, but it cleans well.' },
      ],
    },
  },
  {
    id: '4',
    name: 'All-Natural Soy Candle',
    description: 'A hand-poured candle made with natural soy wax and essential oils, in a reusable jar.',
    category: 'Home Goods',
    price: 1499,
    images: ['https://placehold.co/1200x675.png'],
    greenScore: 7,
    carbonFootprint: '0.8 kg CO₂e',
    certifications: ['Vegan'],
    brand: 'AuraScents',
    reviews: {
      rating: 4.6,
      count: 98,
      items: [],
    },
  },
  {
    id: '5',
    name: 'Reusable Shopping Bag',
    description: 'Durable and foldable shopping bag made from recycled plastic bottles. Say no to single-use plastic.',
    category: 'Accessories',
    price: 799,
    images: ['https://placehold.co/1200x675.png'],
    greenScore: 10,
    carbonFootprint: '0.5 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'CarryGreen',
    reviews: {
      rating: 5.0,
      count: 301,
      items: [],
    },
  },
  {
    id: '6',
    name: 'Hemp Backpack',
    description: 'A stylish and durable backpack made from natural hemp fiber, a highly sustainable crop.',
    category: 'Accessories',
    price: 5999,
    images: ['https://placehold.co/1200x675.png'],
    greenScore: 9,
    carbonFootprint: '4.5 kg CO₂e',
    certifications: ['Organic'],
    brand: 'HempWorks',
    reviews: {
      rating: 4.8,
      count: 55,
      items: [],
    },
  },
   {
    id: '7',
    name: 'Upcycled Denim Jacket',
    description: 'A classic denim jacket given a new life through creative upcycling. Each piece is unique.',
    category: 'Apparel',
    price: 7499,
    images: ['https://placehold.co/1200x675.png'],
    greenScore: 8,
    carbonFootprint: '3.2 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'ReJean',
    reviews: {
      rating: 4.9,
      count: 42,
      items: [],
    },
  },
  {
    id: '8',
    name: 'Cork Yoga Mat',
    description: 'An antimicrobial and non-slip yoga mat made from sustainable cork and natural rubber.',
    category: 'Fitness',
    price: 4999,
    images: ['https://placehold.co/1200x675.png'],
    greenScore: 9,
    carbonFootprint: '2.8 kg CO₂e',
    certifications: ['FSC Certified Cork'],
    brand: 'ZenCork',
    reviews: {
      rating: 4.7,
      count: 76,
      items: [],
    },
  },
];

export const categories = [
  { name: 'All', value: 'all' },
  { name: 'Apparel', value: 'apparel' },
  { name: 'Home Goods', value: 'home-goods' },
  { name: 'Personal Care', value: 'personal-care' },
  { name: 'Accessories', value: 'accessories' },
  { name: 'Fitness', value: 'fitness' },
];

export const brands = [
  { name: 'All Brands', value: 'all' },
  { name: 'EcoThreads', value: 'ecothreads' },
  { name: 'GreenGlass', value: 'greenglass' },
  { name: 'NatureBrush', value: 'naturebrush' },
  { name: 'AuraScents', value: 'aurascents' },
  { name: 'CarryGreen', value: 'carrygreen' },
  { name: 'HempWorks', value: 'hempworks' },
  { name: 'ReJean', value: 'rejean' },
  { name: 'ZenCork', value: 'zencork' },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: '10 Simple Swaps for a More Sustainable Kitchen',
    description: 'Discover easy-to-implement changes that can make your kitchen more eco-friendly, from reusable wraps to composting tips.',
    category: 'Tips & Tricks',
    date: 'April 22, 2024',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'sustainable kitchen',
  },
  {
    id: 2,
    title: 'The Ultimate Guide to Ethical Fashion',
    description: 'Learn what to look for when shopping for clothes to ensure your wardrobe is as kind to the planet as it is to people.',
    category: 'Ethical Fashion',
    date: 'April 15, 2024',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'ethical fashion',
  },
  {
    id: 3,
    title: 'Brand Spotlight: The Story Behind EcoThreads',
    description: 'Go behind the scenes with the founders of EcoThreads and learn about their mission to create stylish, sustainable apparel.',
    category: 'Brand Spotlight',
    date: 'April 8, 2024',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fashion brand',
  },
];
