import type { Product, BlogPost } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Cotton T-Shirt',
    description: 'A soft, comfortable t-shirt made from 100% organic cotton, grown without harmful pesticides.',
    category: 'Apparel',
    price: 1999,
    images: ['/cotton-eco-threads1.png', '/cotton-eco-threads2.png', '/cotton-eco-threads3.png'],
    greenScore: 9,
    carbonFootprint: '2.1 kg CO₂e',
    certifications: ['GOTS', 'Fair Trade'],
    brand: 'EcoThreads',
    reviews: {
      rating: 4.8,
      count: 120,
      items: [
        { id: 'r1', author: 'Jane D.', rating: 5, date: '2024-05-10', comment: 'Incredibly soft and fits perfectly. You can feel the quality. Worth every penny!' },
        { id: 'r2', author: 'Mike P.', rating: 4, date: '2024-05-12', comment: 'Great t-shirt, very comfortable. I wish it came in more colors though.' },
        { id: 'r3', author: 'Sarah K.', rating: 5, date: '2024-05-15', comment: 'My new favorite shirt. I love that it\'s ethically made.' },
      ],
    },
  },
  {
    id: '2',
    name: 'Recycled Glass Tumblers',
    description: 'Set of four drinking glasses made from 100% recycled glass, perfect for any beverage.',
    category: 'Home Goods',
    price: 299,
    images: ['/recycled-glass-tumblers1.png', '/recycled-glass-tumblers2.png'],
    greenScore: 8,
    carbonFootprint: '1.5 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'GreenGlass',
    reviews: {
      rating: 4.9,
      count: 85,
      items: [
        { id: 'r4', author: 'Tom W.', rating: 5, date: '2024-04-20', comment: 'These glasses are beautiful and have a nice weight to them. Very high quality.' },
        { id: 'r5', author: 'Emily R.', rating: 5, date: '2024-04-25', comment: 'I love the subtle green tint. They look great in my kitchen.' },
      ],
    },
  },
  {
    id: '3',
    name: 'Bamboo Toothbrush Set',
    description: 'A pack of four biodegradable toothbrushes with handles made from sustainably sourced bamboo.',
    category: 'Personal Care',
    price: 999,
    images: ['/bamboo-toothbrush-set.png'],
    greenScore: 10,
    carbonFootprint: '0.1 kg CO₂e',
    certifications: ['FSC Certified Bamboo'],
    brand: 'NatureBrush',
    reviews: {
      rating: 4.7,
      count: 213,
      items: [
        { id: 'r6', author: 'David L.', rating: 5, date: '2024-05-01', comment: 'Good for my teeth and good for the planet. Makes me happy.' },
        { id: 'r7', author: 'Jessica M.', rating: 4, date: '2024-05-05', comment: 'The bristles are a bit softer than I expected, but it cleans well.' },
      ],
    },
  },
  {
    id: '4',
    name: 'All-Natural Soy Candle',
    description: 'A hand-poured candle made with natural soy wax and essential oils, in a reusable jar.',
    category: 'Home Goods',
    price: 1499,
    images: ['/all-natural soy-candle.png'],
    greenScore: 7,
    carbonFootprint: '0.8 kg CO₂e',
    certifications: ['Vegan'],
    brand: 'AuraScents',
    reviews: {
      rating: 4.6,
      count: 98,
      items: [],
    },
  },
  {
    id: '5',
    name: 'Reusable Shopping Bag',
    description: 'Durable and foldable shopping bag made from recycled plastic bottles. Say no to single-use plastic.',
    category: 'Accessories',
    price: 799,
    images: ['/reusable-shopping-bag.png'],
    greenScore: 10,
    carbonFootprint: '0.5 kg CO₂e',
    certifications: ['Recycled'],
    brand: 'CarryGreen',
    reviews: {
      rating: 5.0,
      count: 301,
      items: [],
    },
  },
  {
    id: '6',
    name: 'Hemp Backpack',
    description: 'A stylish and durable backpack made from natural hemp fiber, a highly sustainable crop.',
    category: 'Accessories',
    price: 5999,
    images: ['/hemp-backpack.png'],
    greenScore: 9,
    carbonFootprint: '4.5 kg CO₂e',
    certifications: ['Organic'],
    brand: 'HempWorks',
    reviews: {
      rating: 4.8,
      count: 55,
      items: [],
    },
  },
   {
    id: '7',
    name: 'Upcycled Denim Jacket',
    description: 'A classic denim jacket given a new life through creative upcycling. Each piece is unique.',
    category: 'Apparel',
    price: 7499,
    images: ['/upcycled-denim-jacket.png'],
    greenScore: 8,
    carbonFootprint: '3.2 kg CO₂e',
    certifications: ['Upcycled'],
    brand: 'ReJean',
    reviews: {
      rating: 4.9,
      count: 42,
      items: [],
    },
  },
  {
    id: '8',
    name: 'Cork Yoga Mat',
    description: 'An antimicrobial and non-slip yoga mat made from sustainable cork and natural rubber.',
    category: 'Fitness',
    price: 4999,
    images: ['/cork-yoga-mat.png'],
    greenScore: 9,
    carbonFootprint: '2.8 kg CO₂e',
    certifications: ['FSC Certified Cork'],
    brand: 'ZenCork',
    reviews: {
      rating: 4.7,
      count: 76,
      items: [],
    },
  },
];

export const categories = [
  { name: 'All', value: 'all' },
  { name: 'Apparel', value: 'apparel' },
  { name: 'Home Goods', value: 'home-goods' },
  { name: 'Personal Care', value: 'personal-care' },
  { name: 'Accessories', value: 'accessories' },
  { name: 'Fitness', value: 'fitness' },
];

export const brands = [
  { name: 'All Brands', value: 'all' },
  { name: 'EcoThreads', value: 'ecothreads' },
  { name: 'GreenGlass', value: 'greenglass' },
  { name: 'NatureBrush', value: 'naturebrush' },
  { name: 'AuraScents', value: 'aurascents' },
  { name: 'CarryGreen', value: 'carrygreen' },
  { name: 'HempWorks', value: 'hempworks' },
  { name: 'ReJean', value: 'rejean' },
  { name: 'ZenCork', value: 'zencork' },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: '10 Simple Swaps for a More Sustainable Kitchen',
    description: 'Discover easy-to-implement changes that can make your kitchen more eco-friendly, from reusable wraps to composting tips.',
    content: [
      "The kitchen is often called the heart of the home, but it can also be a major source of waste. From single-use plastics to food scraps, the environmental footprint of our kitchens can be significant. The good news is that making a positive change is easier than you think! By swapping out a few everyday items for more sustainable alternatives, you can drastically reduce your waste and create a healthier home and planet.",
      "Here are 10 simple swaps to get you started on your journey to a zero-waste kitchen:",
      "1. Ditch Plastic Wrap for Beeswax Wraps: A natural, reusable, and biodegradable alternative to cling film. They're perfect for covering bowls, wrapping sandwiches, or storing leftover vegetables.",
      "2. Switch to Reusable Produce Bags: Say goodbye to flimsy plastic produce bags at the grocery store. Cloth or mesh bags are durable, washable, and prevent countless plastic bags from ending up in landfills.",
      "3. Embrace the Swedish Dishcloth: These amazing cloths, made from cellulose and cotton, are super absorbent and can replace up to 17 rolls of paper towels. They can be washed and reused for months.",
      "4. Start a Compost Bin: Don't throw away valuable food scraps! Composting fruit and vegetable peels, coffee grounds, and eggshells enriches soil and reduces the amount of waste sent to the landfill, where it would otherwise produce methane gas.",
      "5. Use Glass Storage Containers: Instead of plastic Tupperware that can stain and warp, invest in a set of glass containers. They're durable, non-toxic, and can go from the freezer to the microwave or oven without any issues.",
      "6. Brew Coffee Sustainably: If you're a coffee lover, consider a French press, pour-over, or reusable coffee pods instead of single-use filters or K-cups.",
      "7. Make Your Own Cleaning Supplies: A simple mixture of vinegar, water, and essential oils in a reusable spray bottle can tackle most cleaning jobs, eliminating the need for harsh chemicals and plastic bottles.",
      "8. Buy in Bulk: The bulk section of your grocery store is your best friend. Bring your own jars and containers to stock up on grains, nuts, spices, and oils, significantly reducing packaging waste.",
      "9. Choose a Bamboo Dish Brush: A bamboo brush with natural fiber bristles is a fantastic, biodegradable alternative to plastic dish sponges, which shed microplastics into our waterways.",
      "10. Grow Your Own Herbs: A small herb garden on your windowsill not only provides fresh ingredients for your meals but also eliminates the plastic packaging that fresh herbs typically come in.",
      "Making these small changes can add up to a big impact. Start with one or two swaps and see how easy it is to build a more sustainable kitchen and lifestyle."
    ],
    category: 'Tips & Tricks',
    date: 'April 22, 2024',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'sustainable kitchen',
    comments: [
        { id: 'c1', author: 'EcoWarrior', comment: 'Great tips! I already use beeswax wraps, but I\'m going to start composting now.', date: '2024-04-23' },
        { id: 'c2', author: 'Sustainable Sam', comment: 'Loved this article. Another tip is to use veggie scraps to make broth!', date: '2024-04-24' },
    ],
  },
  {
    id: 2,
    title: 'The Ultimate Guide to Ethical Fashion',
    description: 'Learn what to look for when shopping for clothes to ensure your wardrobe is as kind to the planet as it is to people.',
    content: [
      "In a world of fast fashion, building a wardrobe that aligns with your values can feel like a daunting task. But what exactly is 'ethical fashion'? It's a broad term that encompasses a focus on environmental sustainability, animal welfare, and social responsibility for the people who make our clothes. It's about choosing quality over quantity and supporting brands that are transparent about their practices.",
      "Navigating the world of sustainable style is much easier when you know what to look for. Here's our guide to making more conscious fashion choices:",
      "1. Understand the Materials: The fabric of your clothes is the first step. Look for natural, low-impact fibers like Organic Cotton (uses less water and no pesticides), Linen (durable and made from the flax plant), Hemp (requires very little water and regenerates soil), and TENCEL™ Lyocell (made from sustainably sourced wood pulp in a closed-loop system). Avoid synthetic materials like polyester and nylon when possible, as they are derived from fossil fuels and shed microplastics when washed.",
      "2. Look for Certifications: Certifications are a great way to verify a brand's claims. Keep an eye out for labels like GOTS (Global Organic Textile Standard) for organic materials, Fair Trade Certified to ensure workers are paid fair wages and have safe working conditions, and B Corp, which signifies a company meets high standards of social and environmental performance, accountability, and transparency.",
      "3. Embrace Secondhand and Vintage: The most sustainable item is the one that already exists! Thrifting, consignment shopping, and clothing swaps are fantastic ways to give garments a second life, reduce waste, and find unique pieces that express your personal style.",
      "4. Prioritize Quality and Longevity: Fast fashion is designed to be disposable. Ethical fashion is the opposite. Invest in well-made, timeless pieces that you will love and wear for years to come. Check the stitching, the fabric quality, and the overall construction of a garment before you buy.",
      "5. Care for Your Clothes: Extend the life of your wardrobe by washing clothes less often, using cold water, and air-drying them. Learning basic mending skills, like sewing on a button or patching a small hole, can also make a huge difference.",
      "By making thoughtful choices, you can create a wardrobe that not only looks good but also does good. Your purchasing power is a vote for the kind of world you want to live in—one where fashion is fair, sustainable, and beautiful for everyone."
    ],
    category: 'Ethical Fashion',
    date: 'April 15, 2024',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'ethical fashion',
    comments: [
        { id: 'c3', author: 'Fashionista', comment: 'This was so informative. I had no idea about some of these certifications.', date: '2024-04-16' },
    ],
  },
  {
    id: 3,
    title: 'Brand Spotlight: The Story Behind EcoThreads',
    description: 'Go behind the scenes with the founders of EcoThreads and learn about their mission to create stylish, sustainable apparel.',
    content: [
      "At AuraGrove, we're proud to partner with brands that share our commitment to sustainability and ethical practices. Today, we're thrilled to shine a spotlight on one of our favorite apparel brands: EcoThreads. More than just a clothing line, EcoThreads is a movement dedicated to proving that style and sustainability can, and should, go hand in hand.",
      "EcoThreads was founded by lifelong friends Maya and Liam, who were disillusioned with the environmental and social impact of the fast fashion industry. 'We saw a gap in the market,' says Maya. 'People wanted beautiful, modern clothing, but they were also becoming more aware of the cost—not just the price tag, but the cost to the planet and the people making the garments.'",
      "Their mission was simple but ambitious: to create a collection of wardrobe essentials that were ethically made, environmentally friendly, and built to last. They started with their signature product, the Organic Cotton T-Shirt, a piece that perfectly embodies their philosophy.",
      "The journey began with sourcing the right materials. 'We spent months researching and visiting suppliers,' Liam explains. 'It was crucial for us to use 100% GOTS certified organic cotton. This ensures that the cotton is grown without harmful pesticides and with significantly less water than conventional cotton. It's better for the farmers, the environment, and for the person wearing the shirt.'",
      "But their commitment didn't stop with the fabric. They partnered with a Fair Trade certified factory in India to produce their garments. This partnership guarantees that every worker involved in making an EcoThreads product is treated with respect, paid a living wage, and works in a safe, healthy environment. 'For us, sustainability is about the entire supply chain,' Maya emphasizes. 'It's a holistic approach.'",
      "From their dyeing process, which uses non-toxic, low-impact dyes, to their plastic-free packaging, every detail is carefully considered. The result is a collection of timeless pieces that feel as good as they look. 'We want our customers to feel a connection to their clothes,' Liam says. 'To know the story behind them and to feel proud of the choice they've made.'",
      "EcoThreads is a testament to the power of conscious consumerism and the positive change that purpose-driven brands can create. We are honored to feature them at AuraGrove and to be a part of their journey toward a more beautiful and sustainable future."
    ],
    category: 'Brand Spotlight',
    date: 'April 8, 2024',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fashion brand',
    comments: [],
  },
];
