// This is an autogenerated file from Firebase Studio.
"use client";

import { useWishlist } from "@/context/WishlistContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Heart } from "lucide-react";
import Link from "next/link";
import { ProductCard } from "@/components/product/ProductCard";

export default function WishlistPage() {
  const { wishlist } = useWishlist();

  if (wishlist.length === 0) {
    return (
      <div className="container mx-auto px-4 md:px-6 py-12">
        <div className="flex items-center justify-center gap-4 mb-8">
          <Heart className="h-10 w-10 text-primary" />
          <h1 className="text-4xl font-bold font-headline">Your Wishlist</h1>
        </div>
        <Card className="max-w-2xl mx-auto transition-all duration-300 hover:shadow-xl hover:-translate-y-1">
          <CardHeader>
            <CardTitle>Your Wishlist is Empty</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">You haven't added any items to your wishlist yet. Browse our collection to find something you love!</p>
          </CardContent>
          <CardFooter>
            <Button asChild>
              <Link href="/shop">Explore Products</Link>
            </Button>
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 md:px-6 py-12">
      <div className="flex items-center justify-center gap-4 mb-8">
        <Heart className="h-10 w-10 text-primary" />
        <h1 className="text-4xl font-bold font-headline">Your Wishlist</h1>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
        {wishlist.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </div>
    </div>
  );
}
