// This is an autogenerated file from Firebase Studio.
"use client";

import { useWishlist } from "@/context/WishlistContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Heart } from "lucide-react";
import Link from "next/link";
import { ProductCard } from "@/components/product/ProductCard";

export default function WishlistPage() {
  const { wishlist } = useWishlist();

  if (wishlist.length === 0) {
    return (
      <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
        <Card className="max-w-2xl mx-auto text-center">
          <CardHeader>
            <div className="mx-auto bg-primary/10 rounded-full p-4 w-fit">
              <Heart className="h-12 w-12 text-primary" />
            </div>
            <CardTitle className="mt-4">Your Wishlist is Empty</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">You haven't added any items yet. Browse our collection to find something you love!</p>
          </CardContent>
          <CardFooter className="justify-center">
            <Button asChild size="lg">
              <Link href="/shop">Explore Products</Link>
            </Button>
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
      <div className="flex flex-col items-center text-center gap-4 mb-12">
        <Heart className="h-12 w-12 text-primary" />
        <h1 className="text-4xl md:text-5xl font-bold">Your Wishlist</h1>
        <p className="text-lg text-muted-foreground max-w-2xl">Your curated collection of future-friendly favorites.</p>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
        {wishlist.map((product) => (
          <ProductCard key={product.id} product={product} />
        ))}
      </div>
    </div>
  );
}
