// This is an autogenerated file from Firebase Studio.
"use client";

import Link from 'next/link';
import { ShoppingCart, User, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from '@/lib/firebase/config';
import { useCart } from '@/context/CartContext';
import { Badge } from '@/components/ui/badge';
import { SidebarTrigger } from '../ui/sidebar';

export function Header() {
  const [user] = useAuthState(auth);
  const { getCartItemCount } = useCart();
  const cartItemCount = getCartItemCount();

  return (
    <header className="bg-background/80 backdrop-blur-sm sticky top-0 z-40 w-full border-b">
      <div className="container mx-auto flex h-16 items-center justify-between px-4 md:px-6">
        <div className="flex items-center gap-2">
           <SidebarTrigger className="md:hidden" />
           <Link href="/" className="hidden md:flex items-center gap-2 font-headline text-2xl font-bold">
            AuraGrove
           </Link>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" asChild>
            <Link href="/cart" aria-label="Shopping Cart" className="relative">
              <ShoppingCart className="h-6 w-6" />
              {cartItemCount > 0 && (
                 <Badge className="absolute -top-2 -right-2 h-5 w-5 justify-center p-0">{cartItemCount}</Badge>
              )}
            </Link>
          </Button>
          <Button variant="ghost" size="icon" asChild>
            <Link href="/account" aria-label="My Account">
              {user ? <Users className="h-6 w-6 text-primary" /> : <User className="h-6 w-6" />}
            </Link>
          </Button>
        </div>
      </div>
    </header>
  );
}
