// This is an autogenerated file from Firebase Studio.
"use client";

import { useAuthState } from "react-firebase-hooks/auth";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { auth } from "@/lib/firebase/config";
import {
  SidebarHeader,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarTrigger,
  SidebarContent,
  SidebarFooter,
} from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator";
import { Leaf, Store, Sparkles, Info, Newspaper, Users } from "lucide-react";

const navLinks = [
  { href: "/shop", label: "Shop", icon: <Store /> },
  { href: "/inspiration", label: "Inspiration", icon: <Sparkles /> },
  { href: "/about", label: "About", icon: <Info /> },
  { href: "/blog", label: "Blog", icon: <Newspaper /> },
];

export function AppSidebar() {
  const [user] = useAuthState(auth);
  const pathname = usePathname();

  const allNavLinks = user
    ? [...navLinks, { href: "/community", label: "Community", icon: <Users /> }]
    : navLinks;

  return (
    <>
      <SidebarHeader>
        <div className="flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2" aria-label="AuraGrove Home">
            <Leaf className="h-8 w-8 text-primary" />
            <span className="text-2xl font-bold text-foreground font-headline">AuraGrove</span>
          </Link>
          <SidebarTrigger />
        </div>
      </SidebarHeader>
      <SidebarContent>
        <SidebarMenu>
          {allNavLinks.map((link) => (
            <SidebarMenuItem key={link.href}>
              <SidebarMenuButton
                asChild
                isActive={pathname === link.href}
                tooltip={{ children: link.label }}
              >
                <Link href={link.href}>
                  {link.icon}
                  <span>{link.label}</span>
                </Link>
              </SidebarMenuButton>
            </SidebarMenuItem>
          ))}
        </SidebarMenu>
      </SidebarContent>
      <SidebarFooter>
        <Separator className="my-2" />
        <p className="text-xs text-muted-foreground p-2">
          &copy; {new Date().getFullYear()} AuraGrove
        </p>
      </SidebarFooter>
    </>
  );
}
