// This is an autogenerated file from Firebase Studio.
"use client";

import { useCart } from "@/context/CartContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Minus, Plus, ShoppingCart, Trash2, ArrowRight } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export default function CartPage() {
  const { cart, removeFromCart, updateQuantity, getCartTotal } = useCart();

  if (cart.length === 0) {
    return (
      <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
        <Card className="max-w-2xl mx-auto text-center">
          <CardHeader>
            <div className="mx-auto bg-primary/10 rounded-full p-4 w-fit">
              <ShoppingCart className="h-12 w-12 text-primary" />
            </div>
            <CardTitle className="mt-4">Your Cart is Empty</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">You haven't added any items to your cart yet. Let's change that!</p>
          </CardContent>
          <CardFooter className="justify-center">
            <Button asChild size="lg">
              <Link href="/shop">Continue Shopping</Link>
            </Button>
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
       <div className="text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-bold">Your Cart</h1>
        <p className="text-lg text-muted-foreground mt-2">Review your items and proceed to checkout.</p>
      </div>
      <div className="grid lg:grid-cols-3 gap-8 items-start">
        <div className="lg:col-span-2">
          <Card>
            <CardContent className="p-0">
              <ul className="divide-y">
                {cart.map((item) => (
                  <li key={item.id} className="flex items-center p-4 sm:p-6">
                    <div className="w-24 h-24 sm:w-32 sm:h-32 rounded-md overflow-hidden mr-6">
                      <Image src={item.images[0]} alt={item.name} width={128} height={128} className="w-full h-full object-cover" />
                    </div>
                    <div className="flex-grow">
                      <Link href={`/product/${item.id}`}><h3 className="font-semibold text-lg hover:text-primary">{item.name}</h3></Link>
                      <p className="text-sm text-muted-foreground">₹{item.price.toFixed(2)}</p>
                       <div className="flex items-center gap-2 border rounded-full p-1 mt-4 w-fit">
                          <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" onClick={() => updateQuantity(item.id, item.quantity - 1)} disabled={item.quantity <= 1}>
                              <Minus className="h-4 w-4" />
                          </Button>
                          <span className="w-8 text-center">{item.quantity}</span>
                          <Button variant="ghost" size="icon" className="h-7 w-7 rounded-full" onClick={() => updateQuantity(item.id, item.quantity + 1)}>
                              <Plus className="h-4 w-4" />
                          </Button>
                       </div>
                    </div>
                    <div className="flex flex-col items-end gap-4 ml-4">
                       <p className="font-semibold text-lg">₹{(item.price * item.quantity).toFixed(2)}</p>
                       <Button variant="ghost" size="icon" onClick={() => removeFromCart(item.id)} className="group rounded-full hover:bg-destructive">
                          <Trash2 className="h-5 w-5 text-muted-foreground transition-colors group-hover:text-destructive-foreground" />
                       </Button>
                    </div>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>
        </div>
        <div className="lg:col-span-1">
          <Card className="sticky top-24">
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-between text-muted-foreground">
                <span>Subtotal</span>
                <span>₹{getCartTotal().toFixed(2)}</span>
              </div>
               <div className="flex justify-between text-muted-foreground">
                <span>Shipping</span>
                <span>Free</span>
              </div>
               <Separator />
               <div className="flex justify-between font-bold text-lg">
                <span>Total</span>
                <span>₹{getCartTotal().toFixed(2)}</span>
              </div>
            </CardContent>
            <CardFooter>
              <Button asChild className="w-full" size="lg">
                <Link href="/checkout">Proceed to Checkout <ArrowRight className="ml-2 h-5 w-5" /></Link>
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  );
}
