
// This is an autogenerated file from Firebase Studio.
"use client";

import type { Product, Review } from '@/lib/types';
import Image from 'next/image';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { ToastAction } from "@/components/ui/toast";
import { useCart } from '@/context/CartContext';
import { useToast } from "@/hooks/use-toast";
import { Star, Leaf, Award, Truck, Recycle, Tag, Building } from 'lucide-react';
import SustainableAlternatives from '@/components/product/SustainableAlternatives';
import { ProductReviews } from './ProductReviews';
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../ui/card';
import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from '@/components/ui/carousel';
import { ReviewForm } from './ReviewForm';

export function ProductDetailClient({ product }: { product: Product }) {
  const { addToCart } = useCart();
  const { toast } = useToast();
  const [reviews, setReviews] = useState<Review[]>(product.reviews.items);

  const handleAddToCart = () => {
    addToCart(product);
    toast({
        title: "Added to cart!",
        description: `"${product.name}" has been added to your cart.`,
        action: <ToastAction asChild altText="View cart"><Link href="/cart">View cart</Link></ToastAction>,
    });
  };

  const handleAddReview = (newReviewData: Omit<Review, 'id' | 'date'>) => {
    const newReview: Review = {
        id: `r${Date.now()}`,
        date: new Date().toISOString(),
        ...newReviewData
    };
    setReviews(prevReviews => [newReview, ...prevReviews]);
  };


  return (
    <div className="py-12">
      <Carousel className="w-full max-w-4xl mx-auto mb-12">
        <CarouselContent>
          {product.images.map((image, index) => (
            <CarouselItem key={index}>
              <div className="p-1">
                <Card>
                  <CardContent className="flex aspect-video items-center justify-center p-0">
                     <Image
                      src={image}
                      alt={`${product.name} - image ${index + 1}`}
                      width={1200}
                      height={675}
                      className="w-full h-full object-cover rounded-lg"
                      data-ai-hint="sustainable product lifestyle"
                    />
                  </CardContent>
                </Card>
              </div>
            </CarouselItem>
          ))}
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>

      <div className="text-left mb-8">
        <h1 className="text-3xl md:text-4xl font-bold font-headline">{product.name}</h1>
        <p className="text-xl text-muted-foreground mt-2">{product.brand}</p>
      </div>

      <div className="grid md:grid-cols-3 gap-8 lg:gap-16">
        <div className="md:col-span-2 space-y-8">
           <Card className="bg-transparent border-none shadow-none">
              <CardHeader>
                  <CardTitle>Description & Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                  <p className="text-base leading-relaxed text-muted-foreground">{product.description}</p>
                  <Separator />
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4">
                      <div className="flex items-start gap-3">
                          <Tag className="h-5 w-5 mt-1 text-primary" />
                          <div>
                              <h4 className="font-semibold">Category</h4>
                              <p className="text-muted-foreground">{product.category}</p>
                          </div>
                      </div>
                      <div className="flex items-start gap-3">
                          <Building className="h-5 w-5 mt-1 text-primary" />
                          <div>
                              <h4 className="font-semibold">Brand</h4>
                              <p className="text-muted-foreground">{product.brand}</p>
                          </div>
                      </div>
                      <div className="flex items-start gap-3">
                          <Award className="h-5 w-5 mt-1 text-primary" />
                          <div>
                              <h4 className="font-semibold">Certifications</h4>
                              <p className="text-muted-foreground">{product.certifications.join(', ')}</p>
                          </div>
                      </div>
                      <div className="flex items-start gap-3">
                          <Leaf className="h-5 w-5 mt-1 text-primary" />
                          <div>
                              <h4 className="font-semibold">Carbon Footprint</h4>
                              <p className="text-muted-foreground">{product.carbonFootprint}</p>
                          </div>
                      </div>
                  </div>
              </CardContent>
          </Card>
        </div>
        <div className="md:col-span-1 space-y-6">
            <Card className="bg-muted">
                <CardHeader>
                    <CardTitle>Purchase Options</CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                    <div className="flex flex-wrap items-center gap-x-4 gap-y-1">
                        <div className="flex items-center gap-1">
                            <Star className="h-5 w-5 text-accent" fill="currentColor" />
                            <span className="font-medium">{product.reviews.rating}</span>
                            <span className="text-muted-foreground">({reviews.length} reviews)</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <Leaf className="h-5 w-5 text-green-600" />
                            <span className="font-medium">Green Score: {product.greenScore}/10</span>
                        </div>
                    </div>
                    
                    <p className="text-3xl font-semibold text-primary">${product.price.toFixed(2)}</p>
                    
                    <Button size="lg" className="w-full" onClick={handleAddToCart}>Add to Cart</Button>
                    
                    <div className="space-y-3 text-sm pt-4">
                        <div className="flex items-center gap-2">
                            <Truck className="h-5 w-5 text-muted-foreground" />
                            <span>Carbon-neutral shipping</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <Recycle className="h-5 w-5 text-muted-foreground" />
                            <span>Eco-friendly packaging</span>
                        </div>
                    </div>
                </CardContent>
            </Card>
        </div>
      </div>
      
      <Separator className="my-12" />

      <SustainableAlternatives product={product} />

      <Separator className="my-12" />

      <div className="space-y-8">
        <Card>
            <CardHeader>
                <CardTitle>Customer Reviews</CardTitle>
                <CardDescription>See what others are saying about this product.</CardDescription>
            </CardHeader>
            <CardContent>
                <ProductReviews 
                    reviews={reviews} 
                    averageRating={product.reviews.rating}
                />
            </CardContent>
        </Card>
        <Card>
            <CardHeader>
                <CardTitle>Write a Review</CardTitle>
                <CardDescription>Share your thoughts about the product with the community.</CardDescription>
            </CardHeader>
            <CardContent>
                <ReviewForm onSubmit={handleAddReview} />
            </CardContent>
        </Card>
      </div>

    </div>
  );
}
