// This is an autogenerated file from Firebase Studio.
"use client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";

export default function ConfirmationPage() {
    return (
        <div className="container mx-auto max-w-2xl px-4 md:px-6 py-12 text-center">
            <Card className="p-8">
                <CardHeader>
                    <CheckCircle2 className="mx-auto h-24 w-24 text-green-500 mb-4" />
                    <CardTitle className="text-4xl font-bold font-headline">Order Confirmed!</CardTitle>
                    <CardDescription className="text-lg text-muted-foreground pt-2">
                        Thank you for your purchase. Your journey towards a more sustainable lifestyle is on its way.
                    </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6">
                    <p>You will receive an email confirmation shortly with your order details and tracking information. We are carefully preparing your items with eco-friendly packaging.</p>
                    <div className="flex justify-center gap-4">
                        <Button asChild>
                            <Link href="/shop">Continue Shopping</Link>
                        </Button>
                        <Button variant="outline" asChild>
                             <Link href="/account">View Your Orders</Link>
                        </Button>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
