// This is an autogenerated file from Firebase Studio.
"use client";

import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/lib/firebase/config";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Loader2, Users, MessageSquare, PlusCircle } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { forumPosts } from "@/lib/mock-data";
import type { ForumPost } from "@/lib/types";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

export default function CommunityPage() {
  const [user, loading] = useAuthState(auth);
  const router = useRouter();
  const [posts, setPosts] = useState<ForumPost[]>(forumPosts);

  useEffect(() => {
    if (!loading && !user) {
      router.push('/account');
    }
  }, [user, loading, router]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <Loader2 className="h-16 w-16 animate-spin" />
      </div>
    );
  }

  if (!user) {
    return null; // or a message encouraging login
  }

  return (
    <div className="container mx-auto max-w-4xl px-4 md:px-6 py-12">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-4">
        <div className="space-y-2">
            <h1 className="text-4xl md:text-5xl font-bold font-headline flex items-center gap-3">
                <Users className="h-10 w-10 text-primary" />
                Community Forums
            </h1>
            <p className="text-lg text-muted-foreground">
              Discuss topics, ask questions, and share your experiences.
            </p>
        </div>
        <Button asChild>
          <Link href="/community/new">
            <PlusCircle className="mr-2 h-5 w-5" />
            Create New Post
          </Link>
        </Button>
      </div>

       <div className="space-y-6">
        {posts.map((post) => (
            <Link href={`/community/${post.id}`} key={post.id} className="block">
                <Card className="transition-all duration-300 hover:shadow-xl hover:-translate-y-1 cursor-pointer">
                    <CardHeader>
                        <CardTitle className="text-xl md:text-2xl group-hover:text-primary">{post.title}</CardTitle>
                        <CardDescription className="flex items-center gap-4 pt-2 text-sm">
                            <div className="flex items-center gap-2">
                                <Avatar className="h-6 w-6">
                                    <AvatarFallback>{post.author.charAt(0)}</AvatarFallback>
                                </Avatar>
                                <span>{post.author}</span>
                            </div>
                            <span>{new Date(post.date).toLocaleDateString()}</span>
                        </CardDescription>
                    </CardHeader>
                    <CardFooter className="text-sm text-muted-foreground flex items-center gap-2">
                        <MessageSquare className="h-4 w-4" />
                        <span>{post.replies.length} {post.replies.length === 1 ? 'Reply' : 'Replies'}</span>
                    </CardFooter>
                </Card>
            </Link>
        ))}
       </div>
    </div>
  );
}
