// This is an autogenerated file from Firebase Studio.
"use client";

import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/lib/firebase/config";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Loader2, Users, MessageSquare, PlusCircle } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { forumPosts } from "@/lib/mock-data";
import type { ForumPost } from "@/lib/types";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

export default function CommunityPage() {
  const [user, loading] = useAuthState(auth);
  const router = useRouter();
  const [posts, setPosts] = useState<ForumPost[]>([]);
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setPosts([...forumPosts]);
    setIsClient(true);
  }, []);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-[60vh]">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="container mx-auto max-w-4xl px-4 md:px-6 py-16 md:py-24">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-12 gap-4">
        <div className="space-y-2">
            <h1 className="text-4xl md:text-5xl font-bold flex items-center gap-3">
                <Users className="h-10 w-10 text-primary" />
                Community Forums
            </h1>
            <p className="text-lg text-muted-foreground">
              Discuss topics, ask questions, and share your experiences.
            </p>
        </div>
        <Button asChild size="lg">
          <Link href="/community/new">
            <PlusCircle className="mr-2 h-5 w-5" />
            Create New Post
          </Link>
        </Button>
      </div>

       <div className="space-y-6">
        {posts.map((post) => (
            <Link href={`/community/${post.id}`} key={post.id} className="block">
                <Card className="transition-shadow duration-300 hover:shadow-xl cursor-pointer">
                    <CardContent className="p-6">
                      <div className="flex flex-col sm:flex-row gap-6">
                        <div className="flex-grow">
                          <h2 className="text-xl font-semibold group-hover:text-primary transition-colors">{post.title}</h2>
                          <div className="flex items-center gap-4 pt-2 text-sm text-muted-foreground">
                              <div className="flex items-center gap-2">
                                  <Avatar className="h-6 w-6">
                                      <AvatarFallback>{post.author.charAt(0)}</AvatarFallback>
                                  </Avatar>
                                  <span>{post.author}</span>
                              </div>
                              {isClient && <span>on {new Date(post.date).toLocaleDateString()}</span>}
                          </div>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground sm:border-l sm:pl-6 sm:text-right">
                          <MessageSquare className="h-5 w-5" />
                          <span className="font-semibold">{post.replies.length}</span>
                          <span>{post.replies.length === 1 ? 'Reply' : 'Replies'}</span>
                        </div>
                      </div>
                    </CardContent>
                </Card>
            </Link>
        ))}
       </div>
    </div>
  );
}
