// This is an autogenerated file from Firebase Studio.
"use client";

import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/lib/firebase/config";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import { Loader2, Users } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function CommunityPage() {
  const [user, loading] = useAuthState(auth);
  const router = useRouter();

  useEffect(() => {
    if (!loading && !user) {
      router.push('/account');
    }
  }, [user, loading, router]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <Loader2 className="h-16 w-16 animate-spin" />
      </div>
    );
  }

  if (!user) {
    return null; // or a message encouraging login
  }

  return (
    <div className="container mx-auto max-w-4xl px-4 md:px-6 py-12">
      <div className="space-y-4 text-center mb-12">
        <Users className="mx-auto h-16 w-16 text-primary" />
        <h1 className="text-4xl md:text-5xl font-bold font-headline">Welcome to the AuraGrove Community</h1>
        <p className="max-w-2xl mx-auto text-lg text-muted-foreground">
          This is a place for our members to connect, share ideas, and support each other on the journey to sustainable living.
        </p>
      </div>

       <div className="grid md:grid-cols-2 gap-8">
            <Card>
                <CardHeader>
                    <CardTitle>Community Forums</CardTitle>
                    <CardDescription>Discuss topics, ask questions, and share your experiences.</CardDescription>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground mb-4">Coming soon!</p>
                    <Button disabled>Go to Forums</Button>
                </CardContent>
            </Card>
             <Card>
                <CardHeader>
                    <CardTitle>Member-Only Workshops</CardTitle>
                    <CardDescription>Join exclusive workshops on DIY projects, sustainable habits, and more.</CardDescription>
                </CardHeader>
                <CardContent>
                     <p className="text-muted-foreground mb-4">Coming soon!</p>
                    <Button disabled>View Workshops</Button>
                </CardContent>
            </Card>
        </div>
    </div>
  );
}
