// This is an autogenerated file from Firebase Studio.
"use client";

import { Card, CardContent, CardHeader } from "@/components/ui/card";
import Image from "next/image";
import Link from "next/link";
import { blogPosts } from "@/lib/mock-data";

export default function BlogPage() {
  
  return (
    <div className="container mx-auto px-4 md:px-6 py-16 md:py-24">
      <div className="space-y-4 text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-bold">EcoChic Blog</h1>
        <p className="max-w-2xl mx-auto text-lg text-muted-foreground">
          Insights, tips, and stories for a more sustainable life.
        </p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        {blogPosts.map((post) => (
          <Link href={`/blog/${post.id}`} key={post.id} className="group">
            <Card className="h-full overflow-hidden transition-shadow duration-300 hover:shadow-xl">
              <CardHeader className="p-0">
                <div className="aspect-w-4 aspect-h-3">
                  <Image
                    src={post.image}
                    alt={post.title}
                    data-ai-hint={post.dataAiHint}
                    width={600}
                    height={400}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                </div>
              </CardHeader>
              <CardContent className="p-6">
                <p className="text-sm text-primary mb-2 font-semibold">{post.category}</p>
                <h2 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors">{post.title}</h2>
                <p className="text-sm text-muted-foreground line-clamp-3">{post.description}</p>
                <p className="text-sm text-muted-foreground mt-4">{post.date}</p>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
    </div>
  );
}
